//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genesis {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GameResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Genesis.GameResources", typeof(GameResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Stages&gt;
        ///  &lt;Stage Order=&quot;1&quot;&gt;
        ///    &lt;BackgroundLayers&gt;
        ///      &lt;Layer Order=&quot;1&quot; Image=&quot;layer1.png&quot; XSpeed=&quot;1&quot; YSpeed=&quot;1&quot; /&gt;
        ///      &lt;Layer Order=&quot;2&quot; Image=&quot;layer2.png&quot; XSpeed=&quot;2&quot; YSpeed=&quot;1&quot; /&gt;
        ///      &lt;Layer Order=&quot;3&quot; Image=&quot;layer3.png&quot; XSpeed=&quot;3&quot; YSpeed=&quot;1&quot; /&gt;
        ///    &lt;/BackgroundLayers&gt;
        ///    &lt;EnemeyWaves&gt;
        ///      &lt;Wave Order=&quot;1&quot;&gt;
        ///        &lt;EnemyDefinition FrameHeight=&quot;11&quot; FrameWidth=&quot;3&quot; FramesPerRow=&quot;1&quot; FramesPerSecond=&quot;2&quot; Width=&quot;3&quot; Height=&quot;2&quot; Order=&quot;1&quot; NumberOfFrames=&quot;3&quot; S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GameDefinition {
            get {
                return ResourceManager.GetString("GameDefinition", resourceCulture);
            }
        }
    }
}
